services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:amd64-latest
    container_name: syncthing
    hostname: ${HOST_NAME}
    environment:
      PUID: ${HOST_USER_UID}
      PGID: ${HOST_USER_GID}
      TZ: ${HOST_TIME_ZONE}
    volumes:
      - ${HOST_DATA_FOLDER}/apps/syncthing/data:/data:rw
      - ${HOST_DATA_FOLDER}/apps/syncthing/config:/config:rw
    expose:
      - ${SYNCTHING_WEB_PORT}
    ports:
      - 21027:21027/udp
      - 22000:22000/udp
      - 22000:22000/tcp
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
      restart_policy:
        condition: on-failure
        max_attempts: 10
    labels:
      io.containers.autoupdate: registry
      traefik.enable: true
      traefik.http.routers.syncthing.entrypoints: websecure
      traefik.http.routers.syncthing.rule: "Host(`syncthing.${HOST_FQDN_LOCAL}`)"
      traefik.http.routers.syncthing.tls: true
      traefik.http.routers.syncthing.tls.certresolver: production
      traefik.http.services.syncthing.loadbalancer.server.port: ${SYNCTHING_WEB_PORT}
      homepage.group: System Services
      homepage.name: SyncThing
      homepage.description: Roll your own Dropbox
      homepage.icon: syncthing.png
      homepage.instance.homenetwork.href: "https://syncthing.${HOST_FQDN_LOCAL}"
      homepage.instance.tailscalenetwork.href: "http://syncthing.${HOST_FQDN_TAILSCALE}"
      glance.name: SyncThing
      glance.icon: sh:syncthing
      glance.description: File sync service
      glance.url: https://syncthing.${HOST_FQDN_LOCAL}
